apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.portName }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.portName }}
  selector:
    {{- include "application.selectorLabels" . | nindent 4 }}
