helmDefaults:
  wait: true
  atomic: true
  timeout: 300

repositories:
   - url: ${{ .Values.HARBOR_HOST }}/${{ .Values.HARBOR_PROJECT_NAME }}
     name: ${{ .Values.HARBOR_PROJECT_NAME }}
     username: {{ .Values.HARBOR_ROBOT_NAME }}
     password: {{ .Values.HARBOR_PASSWORD }}
     oci: true

environments:
  development:
  production:

releases:
  - name: {{ .Values.APPLICATION_NAME }}-env-{{ .Environment.Name }}
    namespace: {{ .Values.NAMESPACE }}
    createNamespace: false
    chart: ${{ .Values.HARBOR_PROJECT_NAME }}/${{ .Values.HARBOR_PROJECT_NAME }}-chart/${{ .Values.APPLICATION_NAME }}
    version: {{ .Values.CHART_TAG }}
    values:
      - imagePull:
          credentials: {{ .Values.IMAGE_PULL_SECRET_CREDENTIALS_BASE64 }}
          secretName: {{ .Values.APPLICATION_NAME }}-env-{{ .Environment.Name }}
      - imagePullSecrets: 
          - name: {{ .Values.APPLICATION_NAME }}-env-{{ .Environment.Name }}
      - image:
          tag: {{ .Values.IMAGE_TAG }}
      - ./values.yaml.gotmpl