helmDefaults:
  wait: true
  atomic: true
  timeout: 300

repositories:
  - url: {{ .Values.HARBOR_HOST | toString }}/{{ .Values.HARBOR_PROJECT_NAME | toString }}
    name: {{ .Values.APPLICATION_NAME | toString }}
    username: "{{ .Values.HARBOR_ROBOT_NAME | toString }}"
    password: {{ requiredEnv "HARBOR_ROBOT_TOKEN" }}
    oci: true

environments:
  development:
  production:

releases:
  - name: {{ .Values.APPLICATION_NAME | toString }}
    namespace: {{ .Values.K8S_NAMESPACE | toString }}
    version: {{ .Values.CHART_VERSION | toString }}
    createNamespace: false
    chart: {{ .Values.HARBOR_PROJECT_NAME | toString }}/{{ .Values.APPLICATION_NAME | toString }}-chart/{{ .Values.APPLICATION_NAME | toString }}
    values:
      - image:
          repository: {{ .Values.HARBOR_HOST | toString }}/{{ .Values.HARBOR_PROJECT_NAME | toString }}/{{ .Values.APPLICATION_NAME | toString }}
      - ./values.yaml.gotmpl