helmDefaults:
  wait: true
  atomic: true
  timeout: 300

repositories:
  - url: {{ .Values.HARBOR_HOST }}/{{ .Values.HARBOR_PROJECT_NAME }}
    name: {{ .Values.HARBOR_PROJECT_NAME }}
    username: {{ .Values.HARBOR_ROBOT_NAME }}
    password: {{ requiredEnv "HARBOR_ROBOT_TOKEN" }}
    oci: true

environments:
  development:
  production:

releases:
  - name: {{ .Values.APPLICATION_NAME }}
    namespace: {{ .Values.K8S_NAMESPACE }}
    version: {{ .Values.CHART_VERSION }}
    createNamespace: false
    chart: {{ .Values.HARBOR_PROJECT_NAME }}/{{ .Values.APPLICATION_NAME }}-chart/{{ .Values.APPLICATION_NAME }}
    values:
      - image:
          repository: {{ .Values.HARBOR_HOST }}/{{ .Values.HARBOR_PROJECT_NAME }}/{{ .Values.APPLICATION_NAME }}
      - ./values.yaml.gotmpl