run-name: ${{ inputs.comment }} [${{ github.ref_name }} ref] ${{ inputs.application }} - ${{ inputs.environment }} by @${{ github.actor }}
name: CI/CD
on:
  workflow_dispatch:
    inputs:
      application:
        description: 'Application for deploy'
        required: true
        default: x10archery-fe
        type: choice
        options:
          - x10archery-fe
      environment:
        type: environment
        required: true
        description: 'environment to deploy, for prod use workflow from tags'
        default: development
      comment:
        description: "comment"
        required: true
        default: "usefull information"
        type: string

defaults:
  run:
    working-directory: ./

env:
  HELM_EXPERIMENTAL_OCI: 1
  DEFAULT_VERSION_CHART: "0.0.0"

jobs:
  check_enviroment:
    runs-on: 'ubuntu-latest'
    if: ${{ always() && !(contains(needs.*.result, 'failure')) && !cancelled() }}
    outputs:
      status: ${{ join(steps.*.conclusion) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: step_development
        name: Development
        if: ${{ inputs.environment == 'development' && github.ref_type != 'tag' }}
        run: |
          echo "Branch [${GITHUB_REF##*/}] would be deployed to [${{ inputs.environment }}]" >> "$GITHUB_STEP_SUMMARY"
          exit 0

      - id: step_production
        name: Production
        if: ${{ inputs.environment == 'production' && github.ref_type == 'tag' }}
        run: |
          echo "Branch [${GITHUB_REF##*/}] would be deployed to [${{ inputs.environment }}]" >> "$GITHUB_STEP_SUMMARY"
          exit 0

      - name: Fail
        if: steps.step_development.conclusion == 'skipped' && steps.step_production.conclusion == 'skipped'
        run: |
          echo "Deploy failed! Production includes only tagged versions, development excludes tagged versions!" >> "$GITHUB_STEP_SUMMARY"
          exit 1

  image_build_and_push:
    runs-on: 'ubuntu-latest'
    if: ${{ always() && !(contains(needs.*.result, 'failure')) && !cancelled() }}
    outputs:
      short_sha: ${{ steps.short_sha_step.outputs.sha }}
      image_version: ${{ steps.set_image_version.outputs.image_version }}
    needs:
      - check_enviroment
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to [Harbor]
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.HARBOR_HOST }}
          username: ${{ vars.HARBOR_ROBOT_NAME }}
          password: ${{ secrets.HARBOR_ROBOT_TOKEN }}

      - name: Get short sha
        uses: benjlevesque/short-sha@v2.1
        id: short_sha_step
        with:
          length: 7

      - name: Set [short_sha] in [GITHUB_OUTPUT]
        run: |
          echo "short_sha=${{ steps.short_sha_step.outputs.sha }}" >> $GITHUB_ENV
          echo "sha=${{ steps.short_sha_step.outputs.sha }}" >> $GITHUB_OUTPUT
          echo "short_sha set up to [${{ steps.short_sha_step.outputs.sha }}]" >> "$GITHUB_STEP_SUMMARY"

      - name: Build and push Docker image [Development version]
        if: ${{ inputs.environment == 'development' && github.ref_type != 'tag' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            "SHA_COMMIT=${{ env.short_sha }}"
            "BRANCH_NAME=${{ github.ref_name }}"
          push: true
          tags: ${{ vars.HARBOR_HOST }}/${{ vars.HARBOR_PROJECT_NAME }}/${{ vars.APPLICATION_NAME }}:${{ env.short_sha }}-dev, ${{ vars.HARBOR_HOST }}/${{ vars.HARBOR_PROJECT_NAME }}/${{ vars.APPLICATION_NAME }}:latest-dev

      - name: Build and push Docker image [Production version]
        if: ${{ inputs.environment == 'production' && github.ref_type == 'tag' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            "SHA_COMMIT=${{ env.short_sha }}"
            "VERSION_TAG=${{ github.ref_name }}"
          push: true
          tags: ${{ vars.HARBOR_HOST }}/${{ vars.HARBOR_PROJECT_NAME }}/${{ vars.APPLICATION_NAME }}:${{ github.ref_name }}, ${{ vars.HARBOR_HOST }}/${{ vars.HARBOR_PROJECT_NAME }}/${{ vars.APPLICATION_NAME }}:latest

      - name: Print image version
        id: set_image_version
        run: |
          if [[ "${{ inputs.environment }}" == "production" && "${{ github.ref_type }}" == "tag" ]]; then
            echo "image_version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
            echo "Image [${{ inputs.environment }}] version is [${{ github.ref_name }}]" >> "$GITHUB_STEP_SUMMARY"
          else
            echo "image_version=${{ env.short_sha }}-dev" >> $GITHUB_OUTPUT
            echo "Image [${{ inputs.environment }}] version is [${{ env.short_sha }}-dev]" >> "$GITHUB_STEP_SUMMARY"
          fi

  trivy-scan:
    runs-on: 'ubuntu-latest'
    if: ${{ always() && !(contains(needs.*.result, 'failure')) && !cancelled() }}
    needs:
      - image_build_and_push
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trivy Cache
        uses: yogeshlonkar/trivy-cache-action@v0
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        id: scan
        continue-on-error: true
        env:
          TRIVY_USERNAME: ${{ vars.HARBOR_ROBOT_NAME }}
          TRIVY_PASSWORD: ${{ secrets.HARBOR_ROBOT_TOKEN }}
        with:
          image-ref: "${{ vars.HARBOR_HOST }}/${{ vars.HARBOR_PROJECT_NAME }}/${{ vars.APPLICATION_NAME }}:${{ needs.image_build_and_push.outputs.image_version }}"
          output: "trivy-results"
          cache-dir: .trivy

      - name: Print result
        if: ${{ steps.scan.conclusion == 'success' }}
        run: |
          cat trivy-results >> "$GITHUB_STEP_SUMMARY"

  helm_prepare_and_push:
      runs-on: 'ubuntu-latest'
      if: ${{ always() && !(contains(needs.*.result, 'failure')) && !cancelled() }}
      needs:
      - image_build_and_push
      container:
        image: ghcr.io/helmfile/helmfile:v1.0.0-rc.7
      environment: ${{ inputs.environment }}
      steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint Helm chart
        run: |
          sed -i "s/version\:.*/version\: ${{ env.DEFAULT_VERSION_CHART }}-${{ needs.image_build_and_push.outputs.short_sha }}/" .helm/${{ vars.APPLICATION_NAME }}/Chart.yaml
          sed -i "s/appVersion\:.*/appVersion\: ${{ env.DEFAULT_VERSION_CHART }}-${{ needs.image_build_and_push.outputs.short_sha }}/" .helm/${{ vars.APPLICATION_NAME }}/Chart.yaml
          helm lint ./.helm/${{ vars.APPLICATION_NAME }}

      - name: Push Helm chart
        run: |
          echo "${{ secrets.HARBOR_ROBOT_TOKEN }}" | helm registry login ${{ vars.HARBOR_HOST }} --username '${{ vars.HARBOR_ROBOT_NAME }}' --password-stdin
          helm package ./.helm/${{ vars.APPLICATION_NAME }}
          helm push ${{ vars.APPLICATION_NAME }}-${{ env.DEFAULT_VERSION_CHART }}-${{ needs.image_build_and_push.outputs.short_sha }}.tgz oci://${{ vars.HARBOR_HOST }}/${{ vars.HARBOR_PROJECT_NAME }}/${{ vars.APPLICATION_NAME }}-chart
          echo "Chart [${{ vars.APPLICATION_NAME }}] pushed as [oci://${{ vars.HARBOR_HOST }}/${{ vars.HARBOR_PROJECT_NAME }}/${{ vars.APPLICATION_NAME }}-chart] version [${{ env.DEFAULT_VERSION_CHART }}-${{ needs.image_build_and_push.outputs.short_sha }}]" >> "$GITHUB_STEP_SUMMARY"
          rm ${{ vars.APPLICATION_NAME }}-${{ env.DEFAULT_VERSION_CHART }}-${{ needs.image_build_and_push.outputs.short_sha }}.tgz

  deploy:
      runs-on: 'ubuntu-latest'
      if: ${{ always() && !(contains(needs.*.result, 'failure')) && !cancelled() }}
      needs:
      - image_build_and_push
      - helm_prepare_and_push
      container:
        image: ghcr.io/helmfile/helmfile:v1.0.0-rc.7
      environment: ${{ inputs.environment }}
      steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        env:
          CHART_VERSION: ${{ env.DEFAULT_VERSION_CHART }}-${{ needs.image_build_and_push.outputs.short_sha }}
          IMAGE_TAG: ${{ needs.image_build_and_push.outputs.image_version }}
          ENVIRONMENT: ${{ inputs.environment }}
          SECRET_NAME: ${{ vars.SECRET_NAME }}
          HARBOR_ROBOT_NAME: ${{ vars.HARBOR_ROBOT_NAME }}
          HARBOR_ROBOT_TOKEN: ${{ secrets.HARBOR_ROBOT_TOKEN }}
        run: |
          echo ${{ secrets.KUBE_CONFIG }} | base64 -d > ~/CONFIG
          export KUBECONFIG=~/CONFIG
          echo "${{ secrets.HARBOR_ROBOT_TOKEN }}" | helm registry login ${{ vars.HARBOR_HOST }} --username '${{ vars.HARBOR_ROBOT_NAME }}' --password-stdin
          helmfile -f .helm/helmfile.yaml -e "${{ env.ENVIRONMENT }}" --state-values-set "HARBOR_HOST=${{ vars.HARBOR_HOST }},HARBOR_PROJECT_NAME=${{ vars.HARBOR_PROJECT_NAME }},APPLICATION_NAME=${{ vars.APPLICATION_NAME }},CHART_VERSION=${{ env.CHART_VERSION }},IMAGE_TAG=${{ env.IMAGE_TAG }},K8S_NAMESPACE=${{ vars.K8S_NAMESPACE }},SECRET_NAME=${{ vars.SECRET_NAME }}" sync
          echo "Chart version: [${{ env.CHART_VERSION }}]" >> "$GITHUB_STEP_SUMMARY"
          echo "Image version: [${{ env.IMAGE_TAG }}]" >> "$GITHUB_STEP_SUMMARY"